### ISSUE TITLE
When will you release the code?

### ISSUE THREAD

**Issue by haoranD** [Xinyu-Yi/TransPose#1]
Hi, 

Thanks for this excellent works.

I am very interested in this work.

Can I ask that will you release your code (including training and testing)? And when will you release it?

Thanks.

**Comment by Xinyu-Yi** [comment]
Hi Haoran,
We would like to release the implementation and evaluation first (hopefully before Aug. 30th). 
We are willing to release the training codes, but it may take me some time to reformat and comment on the codes. We would like to release this later.

**Comment by haoranD** [comment]
Many thanks for your reply. Looking forward to your code.

Best Wishes.
