### ISSUE TITLE
Can I use the results of the article into VRChat?

### ISSUE THREAD

**Issue by SlimeVRX** [Xinyu-Yi/TransPose#12]
Dear the author of the article Transpose  

I am a student at the University of Danang in Vietnam. 

I want to use the results of the paper "Real-time 3D Human Translation and Pose Estimation with Six Inertial Sensors" into VRChat.

Please allow me to conduct research for academic purposes. 

Thank you very much!

Link:
https://twitter.com/VRChat/status/1493314642071986182
https://twitter.com/Tn23008624/status/1494618444821839877

**Comment by Xinyu-Yi** [comment]
Sure. For research purposes, just go ahead.

**Comment by NoLoPhe** [comment]
Thanks the author! If possible can you share the Unity code? If you're too busy, I'll find out myself.

**Comment by Xinyu-Yi** [comment]
I'm a little busy (lazy) for the unity code :). I would like to release the unity code in the following work (coming very soon...)

**Comment by NoLoPhe** [comment]
Ok :)) Looking forward to your next work!
