### ISSUE TITLE
vertex_id

### ISSUE THREAD

**Issue by hengrui1012** [Xinyu-Yi/TransPose#13]
Very nice work! I have a question about the smpl vertex index. In the smpl model, we need to manually select some vertices and place virtual sensors on these vertices. Each of these vertices corresponds to an index. I would like to ask you how you get these indices? Is it by calculation or do you get them through unity?

**Comment by Xinyu-Yi** [comment]
Hi, the vertices are just approximately selected, from a SMPL model. The indices are read out from Meshlab. Do not use unity, as it adds additional vertices to the mesh to perform rendering.

**Comment by hengrui1012** [comment]
> Hi, the vertices are just approximately selected, from a SMPL model. The indices are read out from Meshlab. Do not use unity, as it adds additional vertices to the mesh to perform rendering.

Thank you very much for your reply! I managed to find the id corresponding to each vertex using meshlab!

**Comment by bryanbocao** [comment]
> Hi, the vertices are just approximately selected, from a SMPL model. The indices are read out from Meshlab. Do not use unity, as it adds additional vertices to the mesh to perform rendering.

Regarding
https://github.com/Xinyu-Yi/TransPose/blob/2b31fd1bf1534c6f9c973fa091c0c8cbcccc7310/preprocess.py#L34-L35
I understand join index ```ji_mask``` is derived from https://github.com/Xinyu-Yi/TransPose/issues/69, but 
**Q1:** how did you get the vertex index ```vi_mask```?
**Q2:** each joint consists of many vertexes according to https://github.com/Meshcapade/wiki/blob/main/assets/SMPL_body_segmentation/smpl/smpl_vert_segmentation.json, did you pick them by manually visualizing the vertexes?

I have searched around but it is not that obvious to me yet. Sorry if I missed that information.

Thanks!

**Comment by bryanbocao** [comment]
I am trying to visualize the joint vertexes manually:
https://github.com/bryanbocao/IMUPoser/blob/0191dccc6ad5e30f7fbf181e0514e47fb631ccd6/scripts/1_preprocessing/visualize_body_part_segmentation_sel_joint.py#L89

https://youtu.be/b1uB3lcNgzI
https://youtu.be/kOCEp2V2yhc

**Comment by bryanbocao** [comment]
I am trying to inspect the 24 joints manually by visualization:
https://gist.github.com/mkocabas/238faa8a24c44d60fb30ffce367f9ec7
https://github.com/bryanbocao/IMUPoser/blob/0191dccc6ad5e30f7fbf181e0514e47fb631ccd6/scripts/1_preprocessing/visualize_body_part_segmentation_sel_joint.py#L89

https://youtu.be/b1uB3lcNgzI
https://youtu.be/kOCEp2V2yhc
