### ISSUE TITLE
errors even if vctoolkit==0.1.5.39

### ISSUE THREAD

**Issue by SizheAn** [Xinyu-Yi/TransPose#16]
Try to run example but get the error:

```
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 27 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
[ERROR:0@6.930] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2767) open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@6.930] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2839) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
```

As stated in the readme file, my vctoolkit==0.1.5.39 but still faces this error.

**Comment by Xinyu-Yi** [comment]
Hi,

I'm not sure about this. I run the codes on Windows. Maybe try to install ffmpeg, and make sure that your OS has a GUI. Also, you can comment the line:

`art.ParametricModel(paths.smpl_file).view_motion([pose], [tran])`

as this line is only used to render the motion (pose + tran) in real-time. Then you may visualize the motion by yourself.

**Comment by whl-007** [comment]
I can not download vctoolkit==0.1.5.39，do you know why？Could you help me？

![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/efd78104-2de8-40f4-9bfd-c3fdd0a621a9)
