### ISSUE TITLE
Please help me modify to fit my sensor!

### ISSUE THREAD

**Issue by SlimeVRX** [Xinyu-Yi/TransPose#17]
Hi!

I'm trying to reproduce paper results using lower-cost IMU.

Since I am not tall enough (1m63) and have not edited the leg_length information, the estimate is not accurate.
I tried and tested a lot to get the first results: [Video Link](https://twitter.com/Tn23008624/status/1521853664763461632)

IMU: I'm supported six Hi229 9-dof from HiPNUC ([datasheet](https://github.com/SlimeVRX/SlimeVRX/blob/main/hipnuc/datasheet/hi229um_cn.md))
Frequency: 50Hz (record 100Hz step=2)

I recorded the data(data_align, data_T_Pose) and modified [live_hi229.py](https://github.com/SlimeVRX/TransPose/blob/main/live_hi229.py) based live_demo.py:
- Put imu (x = Left, y = Up, z = Forward)
  - record data_align in 10s length: 500 frame
  - data_align[50:300]: align
- Stand straight in T-pose
  - record data_T_Pose in 60s length: 2999 frame
  - data_T_Pose[50:300]: T_Pose
- Demo
  - data_T_Pose[500:2980]: action

The acceleration read from Noitom is global. **But in my data: the acceleration is local, and the quaternion is local.**
I don't know how to convert local to global acceleration, the local accelerometer is passed to the model. This could be the reason the body estimate is not accurate.

Can you help me revise the code to fit my data? ([live_hi229.py](https://github.com/SlimeVRX/TransPose/blob/main/live_hi229.py))
If you are too busy, read through the code once and give me some advice. Thanks a lot!

**Comment by Xinyu-Yi** [comment]
Hi!

I have several questions. Could you find out these things:

1) Which coordinate frame is the sensor "quaternion" expressed in? Is it the global inertial frame (shared by all IMUs)?

2) Which coordinate frame is the sensor acceleration expressed in? Is it the sensor frame (rotated together with the sensor)?

3) Make sure the unit of the acceleration? Is it g or m/s^2? Is the acceleration = g when the sensor is still (or = 0)?

If you can find out these things, I can help you with your code.


p.s. If you speak Chinese, you can send your wechat to me.

**Comment by SlimeVRX** [comment]
I don't speak Chinese, but I have WeChat, please add me!
![image](https://user-images.githubusercontent.com/99313947/166974384-1cf88b67-376d-4ca9-a4e9-c3ce64a817ca.png)

**Comment by SlimeVRX** [comment]
> Hi!
> 
> I have several questions. Could you find out these things:
> 
> 1. Which coordinate frame is the sensor "quaternion" expressed in? Is it the global inertial frame (shared by all IMUs)?
> 2. Which coordinate frame is the sensor acceleration expressed in? Is it the sensor frame (rotated together with the sensor)?
> 3. Make sure the unit of the acceleration? Is it g or m/s^2? Is the acceleration = g when the sensor is still (or = 0)?
> 
> If you can find out these things, I can help you with your code.
> 
> p.s. If you speak Chinese, you can send your wechat to me.

I set the sensor in 9-DOF AHRS mode. I record the data of each sensor, without a combination of sensors.
1. Quaternion is local, and not shared by all IMUs.
2. Acceleration is expressed in the sensor frame (rotated together with the sensor).
3. Unit of acceleration is m/s^2. Unit of raw acceleration is mG but I converted it to m/s^2 using the formula *9.81/2^10. When the sensor is still, the acceleration value is shown in the figure below.

![image](https://user-images.githubusercontent.com/99313947/166979458-b0db8537-a1fe-4d0b-8d15-e72cacfe6cee.png)

**Comment by Xinyu-Yi** [comment]
You just need to convert the acceleration to global. Then check whether your code can work.

You can debug by:
1) put all 6 imus on the desk, keep them still.
2) run your live demo (you do not need to wear or align the imus), and print the calibrated measurements sent to the network. You should get all identity rotation matrix and nearly-zero accelerations, Then throw a sensor into the air (if you can do this), and you will get g acceleration in y axis

**Comment by SlimeVRX** [comment]
I followed your instructions to debug:
1. put all 6 imus on the desk, keep them still. Recorded the data [Stand](https://github.com/SlimeVRX/TransPose/blob/main/read_data).
2. run [live_debug.py](https://github.com/SlimeVRX/TransPose/blob/main/live_debug.py). I get the values rotation matrix and nearly-zero accelerations.

Acc [6,3]
![image](https://user-images.githubusercontent.com/99313947/167105741-a6a5d47b-e67a-4d8e-9ff1-3913944c5f54.png)

Ori [6,3,3]
![image](https://user-images.githubusercontent.com/99313947/167105894-6ab7b6b1-d7cd-4dc4-a625-f57b252b060e.png)

![image](https://user-images.githubusercontent.com/99313947/167107158-5c67e586-61ed-4f74-bcc7-1a55af68bf9e.png)

![image](https://user-images.githubusercontent.com/99313947/167107223-817a390e-a09f-4c06-a23f-68080663ad62.png)

![image](https://user-images.githubusercontent.com/99313947/167107290-0e8d5e39-8fdc-4e71-a21e-a99a88933d64.png)

![image](https://user-images.githubusercontent.com/99313947/167107335-4c8864aa-f86c-46ca-b6aa-6d9c234bf36e.png)

![image](https://user-images.githubusercontent.com/99313947/167107386-37825f00-bf16-49dd-abc9-4f88ab30ccd1.png)
