### ISSUE TITLE
如何获取total capture数据集

### ISSUE THREAD

**Issue by mubai-code** [Xinyu-Yi/TransPose#19]
我给作者发邮件了，但是没有收到回复，请问我要以什么样的格式来发邮件呢

**Comment by mubai-code** [comment]
是要问他要账号你那还是怎么进行数据集的授权，不知道啊

**Comment by Xinyu-Yi** [comment]
你去下载的时候应该会提示输入账号密码，这个需要你发邮件获得TotalCapture作者的同意

**Comment by whl-007** [comment]
请问您解决了raw_totalcapture_official_dir = 'data/dataset_raw/TotalCapture/official'    # contain official gt (S1/acting1/gt_skel_gbl_pos.txt)  ， 这个gt数据集的问题了吗  ，

**Comment by SherlockHarris** [comment]
> 请问您解决了raw_totalcapture_official_dir = 'data/dataset_raw/TotalCapture/official' # contain official gt (S1/acting1/gt_skel_gbl_pos.txt) ， 这个gt数据集的问题了吗 ，

请问您现在解决了吗？可以的话可以交流一下吗？2985694296@qq.com，这是我的邮箱
