### ISSUE TITLE
To reproduce this paper, there are some problems that need to be consulted

### ISSUE THREAD

**Issue by xdtcssdi** [Xinyu-Yi/TransPose#2]
[git repository](https://github.com/xdtcssdi/transpose_mysensor)
I try to reproduce it based on your paper and the source code of dip. Initially got the posture and displacement, but did not reach your effect. The guess may be that the effect of fineturning is not good. Can you advise me. I also sent a message to your mailbox.

**Comment by Xinyu-Yi** [comment]
I see. But I'm not sure about your problem. let's use email or wechat. I'll send you.

**Comment by xdtcssdi** [comment]
微信是15088893307
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xinyu-Yi/TransPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月15日(星期天) 晚上9:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xinyu-Yi/TransPose] To reproduce this paper, there are some problems that need to be consulted (#2)





 
I see. But I'm not sure about your problem. let's use email or wechat. I'll send you.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
