### ISSUE TITLE
Unity3D example scene

### ISSUE THREAD

**Issue by timchiu9781** [Xinyu-Yi/TransPose#23]
Hello Xinyu, can you describe more detail about how to build an example scene in Unity.
I stucked in the step in "Server start. Waiting for unity3d to connect"

![image](https://user-images.githubusercontent.com/55866531/172334520-0047ee3d-0dda-475b-a074-19022dd6ab16.png)

Big thanks!

**Comment by SlimeVRX** [comment]
You should search for the keyword ["How to import Unity Packages"](https://docs.unity3d.com/560/Documentation/Manual/AssetPackages.html)

1. Import Package -> "visualizer.unitypackage"

![image](https://user-images.githubusercontent.com/99313947/172438820-0eb039c5-6600-482a-a0f2-6eddf250c1ec.png)

2. All -> Import

![image](https://user-images.githubusercontent.com/99313947/172439188-2a4b0307-69ee-44c7-b9bc-97a6e6ef0524.png)

3. Project -> Assets -> Scenes -> Example

![image](https://user-images.githubusercontent.com/99313947/172440445-ebdc629b-a272-474a-90f2-48dbe68e619e.png)

4. Run Python code -> "Server start. Waiting for unity3d to connect"

5. Unity -> Play
