### ISSUE TITLE
AMASS data mismatch

### ISSUE THREAD

**Issue by TowoC** [Xinyu-Yi/TransPose#24]
Hello Xinyu

I'm trying to download the raw AMASS dataset.
But there got some problem.

In the config.py, the comment is shown below
![image](https://user-images.githubusercontent.com/55866531/172989479-636bb38f-1975-41dd-b91e-966ecdbe0d10.png)

But I can't find the amass_data like your comment in the config.py.
So I want to ask you if you have the dataset source like your comment in the code. 

For example, I can not find BioMotionLab_NTroje and MPI_Limits Dataset at download page in AMASS website.
And in the AMASS download page, there are 24 dataset shown in the page.
But I only see 18 dataset in your comment.
I think maybe the AMASS group add more dataset on their page.

But if I want to reproduce your excellent work, how can I do.

Can you help me? Thank you!!

Tim

**Comment by Xinyu-Yi** [comment]
Hi Tim,

I actually downloaded AMASS dataset some years ago, and it may be changed now. But I think the results won't be changed much if you use the new AMASS dataset. You can just modify this code to use more AMASS subsets (the more, the better).

Best,
Xinyu Yi

**Comment by timchiu9781** [comment]
Hi Xinyu,
Sorry that I have a presumptuous request.
Can I have your training code of Transpose?
I have already try to implement this work for a month.
But there still have some problem that is hard to be solved.

If that is OK, please send the training code to this email.
No comment version is OK with me, I will try to figure it out.

Thanks a lot.

Best regards,
*Tim Chiu 邱庭威*


TingWei Chiu ***@***.***> 於 2022年6月13日 週一 上午11:19寫道：

**Comment by Jaceyxy** [comment]
@Xinyu-Yi  
hi，I see many download options in the amass dataset. Which one should I download?
![image](https://user-images.githubusercontent.com/54926038/188834595-e36dad62-365b-42bf-b1a2-7e38f3fc2a18.png)
thanks！

**Comment by TowoC** [comment]
Hi Xinyu,
Thanks for your reply.
I will download more dataset from AMASS.
Thanks again for your help and amazing work.

Looking forward to release the PIP source code.
Good luck!

Best regards,
*Tim Chiu 邱庭威*


Xinyu Yi ***@***.***> 於 2022年6月11日 週六 下午8:17寫道：
