### ISSUE TITLE
骨骼坐标系

### ISSUE THREAD

**Issue by Jaceyxy** [Xinyu-Yi/TransPose#26]
请问骨骼坐标系是怎么定义的呢？谢谢了

**Comment by Xinyu-Yi** [comment]
骨骼坐标系是SMPL的坐标系

**Comment by Jaceyxy** [comment]
![image](https://user-images.githubusercontent.com/54926038/179401616-1f61a815-01fe-4859-bbdd-920693add991.png)
请问这里的Rm bone[i]都是单位阵嘛？

**Comment by Xinyu-Yi** [comment]
是的，我们只使用了T-pose calibration

**Comment by Jaceyxy** [comment]
非常感谢

**Comment by Xinyu-Yi** [comment]
> 您好，我想咨询一下关于加速度的处理 我的理解流程如下： 1.Tpose状态下先求解a M offset[i]论文中对应公式如下 ![image](https://user-images.githubusercontent.com/54926038/179743464-10fc68f3-dc24-4cf3-add2-81d90abbcf8b.png) 2.然后继续求得a M bone[i] 然而在阅读代码时，如下： ![image](https://user-images.githubusercontent.com/54926038/179744041-fdce814d-8cbb-4b9d-ba52-e711f1c2e4d1.png) 我想询问的是代码中的accs是否已经问加速度在世界坐标系下的值 ![image](https://user-images.githubusercontent.com/54926038/179744381-3b6298e7-8444-4c2f-a58f-c685afd19ac2.png) 我注意到加速度的获取有这样一个操作，不知道是否与其相关

我们用的这个传感器读的是北东地下的加速度，而且有重力加速度。所以是这样操作的。如果一般的传感器提供设备坐标系下的本地加速度，就左乘朝向即可。如果知道自己的重力加速度，直接减去对应值即可，不需要论文里这些操作。最后拿到第一帧根节点坐标系下的净加速度即可
