### ISSUE TITLE
totalcapture   trans处理

### ISSUE THREAD

**Issue by Jaceyxy** [Xinyu-Yi/TransPose#27]
你好，请问在对totalcapture处理过程中
代码如下
pos[:, :, 0].neg_()   #对Tensor中的每个元素取负
pos[:, :, 2].neg_()
 trans.append(pos[:, 2] - pos[:1, 2])   # N, 3   #相当与每帧的脊柱坐标减去第一帧的脊柱坐标
请问为什么要进行neg操作，此外左右脚数据好像没有使用到
十分感谢

**Comment by Xinyu-Yi** [comment]
totalcapture使用的全局坐标系好像和我们的 x z 轴是相反的，所以取负数

**Comment by Jaceyxy** [comment]
十分感谢
