### ISSUE TITLE
Is TotalCapture part of both your training and testing dataset?

### ISSUE THREAD

**Issue by VimalMollyn** [Xinyu-Yi/TransPose#29]
Hi, I was going through the preprocessing script and I saw that the TotalCapture dataset from AMASS was included in your training dataset. Doesn't this contain the motion sequences from the testing set, or am I missing something?

**Comment by Xinyu-Yi** [comment]
You are right. The synthetic totalcapture is used in training and the real measurements are used in evaluation.
