### ISSUE TITLE
AMASS pretraining details

### ISSUE THREAD

**Issue by jyf588** [Xinyu-Yi/TransPose#3]
Hi Xinyu,

Thank you and your colleagues for this great work. Really impressed by the results.

We are working on a project where part of your project might be very helpful. Specifically, how do you select the *subset* of AMASS and generate the synthetic data (~1200 min out of total 60 hours)? Do you need to downweight some common motions (like walking) and upweight some rare motions during training?

I am also wondering the details about how you place the virtual IMU sensors on the SMPL model -- is it same as DIP? Would it be possible for you to send me (yifengj at stanford.edu) the training / data generation code? ("Dirty" and uncommented version is totally fine.)

Thanks a lot!
Yifeng

**Comment by Xinyu-Yi** [comment]
Hi Yifeng,

In AMASS dataset, most motions are in 59, 60, 100, and 120 fps. We just directly use the 59 and 60 fps motions, and downsample the 120fps motions into 60fps (and discard the 100fps motions). No other sampling is performed.

For the virtual IMUs, we just approximately select 6 vertices on the SMPL model as the positions of the IMUs. Then we synthesize virual accelerations and orientations as stated in the paper. During training, normal noises are added to simulate real IMUs.

Xinyu

**Comment by jyf588** [comment]
Hi Xinyu,

Thanks! AMASS has 2992min of motion; are you saying that after discarding all 100fps motions we will be left with 1217min (Table 1)?...

-Yifeng

**Comment by Xinyu-Yi** [comment]
Hi Yifeng,

In fact, I download the AMASS dataset maybe two years ago. I can't remember which datasets it contains. And after preprocessing there is totally 1217min left. All I do is just downsampling to 60fps and synthesize the acc/ori, then they will be used in training. It seems that AMASS has grown bigger and I believe more data will improve the results.

Xinyu

**Comment by jyf588** [comment]
I see. Thanks! Would it be possible for you to send me the training or data synthesis code? Uncommented version is okay.

-Yifeng

**Comment by Xinyu-Yi** [comment]
Hi, I have released the AMASS synthesis code. You can check the preprocess.py if needed.
