### ISSUE TITLE
Totalcapture 

### ISSUE THREAD

**Issue by Jaceyxy** [Xinyu-Yi/TransPose#30]
![image](https://user-images.githubusercontent.com/54926038/184333851-79d3a6ff-e6a1-4ab0-bb9a-9230d8012c50.png)
我发邮件向DIP的作者询问是否能获取totalcapture 的相关数据，他向我提供了该链接，但好像没有相关数据

**Comment by Jaceyxy** [comment]
作者已经向我提供了smpl 相关数据，有需要可以向作者询问该数据，后续马上会在dip数据集中公布该数据

**Comment by plussea** [comment]
请问能提供ground truth smpl pose数据的DIP作者邮箱吗，或者能直发一份ground truth smpl pose。我的邮箱1919366379@qq.com谢谢

> 作者已经向我提供了smpl 相关数据，有需要可以向作者询问该数据，后续马上会在dip数据集中公布该数据

**Comment by whl-007** [comment]
是的，我已经解决了DIP_recalculate的问题，但是下载的文件没有关于official gt的文件，我在AMASS下载的TotalCapture也没有以txt格式的gt，这是什么情况呢？
raw_totalcapture_official_dir = 'data/dataset_raw/TotalCapture/official'    # contain official gt (S1/acting1/gt_skel_gbl_pos.txt)
