### ISSUE TITLE
我在使用自己的imu接入时遇到了问题

### ISSUE THREAD

**Issue by YYYYYYYYZ** [Xinyu-Yi/TransPose#31]
我使用mpu6050接入transpose，估计的姿势偏差很大，让我怀疑我的陀螺仪数据或加速度数据的处理上有问题（我传入的四元数w,x,y,z 加速度已经左乘了旋转矩阵）
您方便的话可以加我的wx：18578640136
在解决后我会把我的接入方案开源出来，麻烦了！

**Comment by Xinyu-Yi** [comment]
您好，你这个6轴imu会有重力方向漂移，我们这个系统要用9轴imu。
另外如果姿态不对，你需要检查输入数据是否为正确值，正确的坐标系，tpose calibration是否正确做了，并相应修改live demo的代码

**Comment by Xinyu-Yi** [comment]
您好，你这个6轴imu会有重力方向漂移，我们这个系统要用9轴imu。
另外如果姿态不对，你需要检查输入数据是否为正确值，正确的坐标系，tpose calibration是否正确做了，并相应修改live demo的代码

**Comment by YYYYYYYYZ** [comment]
是的，六轴会漂移，但因为漂移短时间内不会累计太多，所以我想进行尝试，再换为九轴。
我想请问一下六个imu传入的姿态需要相同的坐标系吗，因为mpu6050是六轴imu，他会以上电时的朝向作为偏航角，意味着如果初始化的时候六个imu朝向不同，他们的偏航角会不一致

**Comment by Xinyu-Yi** [comment]
哦对，这样不可以，那你需要先把6个imu放在一排置零

**Comment by YYYYYYYYZ** [comment]
谢谢您的回复！我努力尝试一下
