### ISSUE TITLE
imu佩戴位置

### ISSUE THREAD

**Issue by meyiao** [Xinyu-Yi/TransPose#36]
您好！请问需要标定imu和关节之间的相对位姿吗？如果佩戴位置不同，网络能很好泛化吗？

**Comment by Xinyu-Yi** [comment]
佩戴的旋转不同是通过calibration确定的。如果位置不同，那没办法工作，需要重新训练网络，否则精度会下降

**Comment by meyiao** [comment]
谢谢！那是不是不同高矮的人，也需要重新训练呢？

**Comment by Xinyu-Yi** [comment]
高矮差别不大的话精度还可以，包括佩戴位置基本差不多的话都可以运行。如果差距过大的话（比如小孩）那可能需要重新训练的

**Comment by meyiao** [comment]
好的，谢谢
