### ISSUE TITLE
Different IMU Set for training and demo

### ISSUE THREAD

**Issue by VimalMollyn** [Xinyu-Yi/TransPose#37]
Hi, I noticed that in the preprocessing script the IMUs used from DIP-IMU are the [left elbow, right elbow, left knee, right knee, head, root] / [7, 8, 11, 12, 0, 2]. Similarly, the locations of the virtual IMUs for AMASS are [left elbow, right elbow, left knee, right knee, head, root] / [18, 19, 4, 5, 15, 0]. 

However, in the paper and in the demo videos, the IMUs are placed on the left and right _**wrists**_, not the left and right _**elbows**_ as in the training. Am I missing something?

**Comment by Xinyu-Yi** [comment]
Hi. In live demos, we place the IMUs on the fore arms near the wrists. It means that the imus measure the orientation of the fore arm bone. When synthesizing IMU data for the public datasets, the orientation of the fore arm is exactly the rotation of the elbow. Regarding to the acceleration, we do not use these joint positions, and instead, we use the vertex position which is near the wrist.

**Comment by bryanbocao** [comment]
Hi @VimalMollyn @Xinyu-Yi, can you help me find which indices correspond to which joints? I searched the code and paper but did not find them. It would be great to point me the reference if I missed that. Thanks!
