### ISSUE TITLE
如何用自己购买的九轴imu复现

### ISSUE THREAD

**Issue by duuuu99** [Xinyu-Yi/TransPose#39]
你好
我看到live_demo.py里你使用了Axis Legacy，请问我该修改哪里来导入我 的imu数据呢
谢谢

**Comment by Jaceyxy** [comment]
我使用自己购买的imu成功了，自己的imu数据要按照论文中的说明经过Calibration与Normalization后输入网络即可，不知道是否能帮到你

**Comment by duuuu99** [comment]
> 我使用自己购买的imu成功了，自己的imu数据要按照论文中的说明经过Calibration与Normalization后输入网络即可，不知道是否能帮到你

嗨
谢谢你
可以加微信详细聊一聊吗
我的微信是 dddu2u22

**Comment by gsygsy96** [comment]
> 我使用自己购买的imu成功了，自己的imu数据要按照论文中的说明经过Calibration与Normalization后输入网络即可，不知道是否能帮到你

你买的是什么型号的imu呀

**Comment by Scout9917** [comment]
> 我用自己购买的imu成功了，自己的imu数据要拍照论文中的说明经过Calibration与Normalization后输入网络即可，不知道是否能帮到你

Hello, can you share your calibration and normalization code? Thanks a million. The following is my email 1241755088@qq.com.

**Comment by GUIMINLONG** [comment]
> 我使用自己购买的imu成功了，自己的imu数据要按照论文中的说明经过Calibration与Normalization后输入网络即可，不知道是否能帮到你

你好，我看live_demo.py 里已经有了calibration 和normalization 过程。但我直接用自己IMU出来的效果完全乱的。请问你有修改代码哪里吗？另外，不知道是否方便告知一下自己IMU传入的数据格式是什么样的？
我看作者源代码里 “d = np.array(strs[:96]).reshape((6, 16))  # first 6 imus” ，这是每个IMU信号有16维吗？我的IMU只有ax,ay,az,mx,my,mz,rx,ry,rz 一共个数据，这样我需要怎么把每个IMU信号凑成源代码中的（6,16）维的数据呢？
谢谢

**Comment by GUIMINLONG** [comment]
> 你好 我看到live_demo.py里你使用了Axis Legacy，请问我该修改哪里来导入我 的imu数据呢 谢谢

Hello, did you solve problem. I also have same situation. My IMU only can outpu ax,ay,az,mx,my,mz,rx,ry,rz, do you know how to convert it to the form which can be directly used in "live_demo.py"

**Comment by Xinyu-Yi** [comment]
不要凑16维，你把旋转和加速度拿出来输给网络就可以了。但我看你的传感器似乎没有读出旋转。我们需要旋转而不是角速度

> > 你好 我看到live_demo.py里你使用了Axis Legacy，请问我该修改哪里来导入我 的imu数据呢 谢谢
> 
> Hello, did you solve problem. I also have same situation. My IMU only can outpu ax,ay,az,mx,my,mz,rx,ry,rz, do you know how to convert it to the form which can be directly used in "live_demo.py"

**Comment by SherlockHarris** [comment]
> 我使用自己购买的imu成功了，自己的imu数据要按照论文中的说明经过Calibration与Normalization后输入网络即可，不知道是否能帮到你

如果可以能请问一下您购买的imu是哪一款吗？我需要一款价格不是那么昂贵的imu
