### ISSUE TITLE
我用自己的IMU跑这个代码为啥双手上臂一直悬浮啊

### ISSUE THREAD

**Issue by 1127098138** [Xinyu-Yi/TransPose#40]
我用自己的IMU跑这个代码为啥双手上臂一直悬浮啊，如下图所示：
![d4f7357ad2e4742bbab04c3ee01faf4](https://user-images.githubusercontent.com/93702292/191250369-4475ddac-cf54-4bf9-916e-30880fb16353.png)

**Comment by duuuu99** [comment]
请问可以加微信交流一下吗
我的微信是dddu2u22

**Comment by Xinyu-Yi** [comment]
可能是calibration没做对
