### ISSUE TITLE
acc_scale issue

### ISSUE THREAD

**Issue by Junlin-Yin** [Xinyu-Yi/TransPose#43]
Hi, I'm currently trying to reproduce your project, and I find ```normalize_and_concat``` function a little bit confusing. You just divide the normalized acceleration by ```acc_scale``` which is 30, and this function is applied to both DIP-IMU and TotalCapture. The problem is, do I need to divide ```acc_scale``` for AMASS dataset as well during pre-training?

Moreover, I find that DIP project simply uses the z-score standardization to "align" different datasets, which is given up in your project. Therefore, I speculate that dividing acceleration by ```acc_scale``` is your way to standardize or align AMASS, DIP-IMU and TotalCapture. Am I right?

**Comment by Xinyu-Yi** [comment]
You need to divide accscale for AMASS dataset.

**Comment by scholars-Lwp** [comment]
I have a few questions that I'm confused about：
1.What are the functions of acc scale and vel scale?
2. Why does it need to be divided by 60 in the tran-b2 link, and what is the speed unit output by tran-b2?

**Comment by Xinyu-Yi** [comment]
I just experimentally found that the max/min value of accelerations in all the datasets is around 30m/s^2 (or 90m/s^2?), so I scale it by 1/30 to ensure similar scale w.r.t the orientation, which is in [-1, 1]

**Comment by Xinyu-Yi** [comment]
The velocity scale is similar to acceleration scale. The 1/60 is delta t between frames. The output velocities should also be rescaled in around [-3, 3], so I use a vel_scale.

**Comment by scholars-Lwp** [comment]
Thank you very much for your answer
