### ISSUE TITLE
Lower limb pose prediction much worse than upper limb prediction

### ISSUE THREAD

**Issue by formidify** [Xinyu-Yi/TransPose#44]
Hi, I've been using the XSens IMU sensors to collect data and run pose prediction using the TransPose algorithm. The sensor placement and configuration follow that of the DIP dataset. I use both single sensor calibration (x=Left, y=Up, z=Forward) and T-pose calibration, like what is done in live_demo.py. However, what I've found, is that upper limb predictions are pretty accurate, but the lower limb predictions are not correct (for example, the Unity avatar is supposed to raise the leg but it is just standing normally). Any possible suggestions, or someone with similar problems?

**Comment by NoLoPhe** [comment]
Hi, I'll just give you a tip. The reason is that your height is not enough, so the acceleration generated is not large enough.
There are 2 ways to solve it:
- You have to kick your feet faster for greater acceleration
- You must find a model taller than 1m75
