### ISSUE TITLE
Can not reproduce test result in TotalCapture

### ISSUE THREAD

**Issue by iamyouno** [Xinyu-Yi/TransPose#47]
Hi, I'm trying to reproduce **test result** using DIP-IMU and TotalCapture datasets.

When run preprocess.py and evaluate.py, It worked well in DIP-IMU, but not in TotalCapture.

Is anyone who reproduce test result with TotalCapture dataset?

Should I change code or some data?

**Comment by yul97** [comment]
> It should reproduce the TotalCapture results in the paper without changing any code (except for some paths in the config). Are you using the ground truths provided by the DIP authors?

I checked it and still haven't solved this problem. Could you tell me whether the ground truths provided by the DIP authors is the dataset shown in the figure？
![image](https://user-images.githubusercontent.com/124663012/217248174-d8486d3e-43c6-46f3-acbb-e623d6003b75.png)

**Comment by syguan96** [comment]
Hi guys, have you solved this problem? My reproduced results are: 
============== offline ================
SIP Error (deg): 62.50 (+/- 22.71)
Angular Error (deg): 50.06 (+/- 17.78)
Positional Error (cm): 28.58 (+/- 10.20)
Mesh Error (cm): 31.46 (+/- 11.38)
Jitter Error (100m/s^3): 1.47 (+/- 2.85)

**Comment by Xinyu-Yi** [comment]
> Hi guys, have you solved this problem? My reproduced results are: ============== offline ================ SIP Error (deg): 62.50 (+/- 22.71) Angular Error (deg): 50.06 (+/- 17.78) Positional Error (cm): 28.58 (+/- 10.20) Mesh Error (cm): 31.46 (+/- 11.38) Jitter Error (100m/s^3): 1.47 (+/- 2.85)

Please send me your saved test results. I will check this.

**Comment by syguan96** [comment]
Hi Xinyu @Xinyu-Yi , I download SMPL annotations of TotalCapture from [the official website](https://dip.is.tuebingen.mpg.de/).

The downloaded SMPL annotation and processed file are uploaded. You can download it from https://cowtransfer.com/s/8388217ba9e340 .

I uncommented `evaluate_pose(paths.totalcapture_dir)`, and then run `python evalaute.py`. You can check it.

**Comment by syguan96** [comment]
And I rendered the results, the predicted mesh shows the wrong poses.  Would you mind sending me the smpl parameters of the TotalCapture you used? My email is shyanguan@sjtu.edu.cn

**Comment by scholars-Lwp** [comment]
@syguan96  
I have the same problem as you. Have you solved it? If so, can you tell me what the problem is?

**Comment by scholars-Lwp** [comment]
I have the same problem as you. Have you solved it? If so, can you tell me what the problem is?

**Comment by Xinyu-Yi** [comment]
Sorry for the late response. I have uploaded the old version of the SMPL pose (obtained from DIP authors) for the TotalCapture dataset. See https://github.com/Xinyu-Yi/PIP/issues/34

**Comment by bryanbocao** [comment]
> Hi guys, have you solved this problem? My reproduced results are: ============== offline ================ SIP Error (deg): 62.50 (+/- 22.71) Angular Error (deg): 50.06 (+/- 17.78) Positional Error (cm): 28.58 (+/- 10.20) Mesh Error (cm): 31.46 (+/- 11.38) Jitter Error (100m/s^3): 1.47 (+/- 2.85)

I got the same results as well. May I know if you solved the problem? Thank you! @syguan96
