### ISSUE TITLE
calibration in AMASS datasets

### ISSUE THREAD

**Issue by iamyouno** [Xinyu-Yi/TransPose#49]
I'm trying to make train.py with your given code and datasets.
I made synthetic amass datasets and checked it worked well in evaluate.py.

Most of train.py was written, but there is difficulty in calibrating amass data.

In the paper, t-pose calibration was used, and to do so, ori_raw and acc_raw values of t-pose are required. 
How can I get data? Are they already in synthetic amass datasets?

In calibration process of the live_demo.py, I can check that smpl2imu and device2bone are created by directly collecting t-pose data.
I'm trying to use a code similar to this, but I don't know how to get ori_raw and acc_raw.

**Comment by Xinyu-Yi** [comment]
The synthetic data do not need calibration as you define the virtual IMUs by yourself. E.g., in my preprocessing codes, the sensor-to-bone rotation is just identity.

**Comment by Xinyu-Yi** [comment]
Calibration is only needed when the IMU-bone extrinsics are unknown.

**Comment by fandulu** [comment]
Hi @Xinyu-Yi , thanks for your great work, may I ask more about the calibration here? 

I can understand your solution of using T-pose to obtain the sensor2bone rotation (So(3)), but I was wondering if the imu frame has an offset in terms of Sim(3) other than So(3), then the bias of accelerations could be more significant in the normalization step.

Is my understanding correct?

**Comment by Xinyu-Yi** [comment]
1. Yes, actually we assume that you put the IMU on the correct positon. Then we only consider the rotation offset. The acceleration will be different if you put the IMU on the wrong position.
2. Yes.

**Comment by fandulu** [comment]
Got it. Thanks very much!
