### ISSUE TITLE
smpl与unity坐标转换的问题请教

### ISSUE THREAD

**Issue by Seeseallllll** [Xinyu-Yi/TransPose#51]
大佬你好，感谢你的工作。
我在使用其他项目计算的SMPLX数据（右手坐标系，X-right，Y-up，Z-forward）截取了前24个节点坐标和trans后导入你创建的unity项目中实现可视化的时候遇到了一些问题，人体动作很扭曲。
想请教你的是，你的代码计算后传输到unity的数据是左手坐标系还是右手坐标系？x,y,z分别都是哪些方向？
MotionController.cs中的坐标转换看得有点懵。请大佬指教

**Comment by Xinyu-Yi** [comment]
发送到unity的是右手坐标系，unity本身用的是左手坐标系，可视化的时候需要变换一下
