### ISSUE TITLE
作者您好，我想问一下 使用unity在线估计的时候 为何延迟会很大 

### ISSUE THREAD

**Issue by LC-86886** [Xinyu-Yi/TransPose#55]
我发现在我佩戴imu做动作时，unity上的模型总是延迟将近10s。而我将数据录制下来，以相同在线方式进行，却进行的十分流畅。

**Comment by Xinyu-Yi** [comment]
我没遇到这个问题

**Comment by GUIMINLONG** [comment]
> 我发现在我佩戴imu做动作时，unity上的模型总是延迟将近10s。而我将数据录制下来，以相同在线方式进行，却进行的十分流畅。

你好，打扰一下。我之前完全没用过unity, 我尝试运行live_demo的时候还是没弄清楚要怎么将用unity接收python的动作数据，并进行可视化展示。不知道你有没有关于这方向实现教程或者案例可以推荐参考一下。
谢谢
