### ISSUE TITLE
同样使用Noitom设备测试后效果不太好

### ISSUE THREAD

**Issue by JLlike77** [Xinyu-Yi/TransPose#56]
嗨作者你好~我也是使用了noitom的设备去做的测试，pose基本一致，也可以跳起来，但我们将位移时序图plot下来的时候发现位移偏差是有点大的，尤其是xz轴，尤其是跑起来的时候，可以请问一下作者大大您有对直接提取上来的raw data做一些什么处理么？比如去噪这些？十分感谢如果您能回复的话~

**Comment by Xinyu-Yi** [comment]
位移确实会有漂移，但看起来应该比较合理。如果需要更准确的位移可以输入腿部的长度。rawdata除了论文里的calibration没做别的处理
