### ISSUE TITLE
how to contact the DIP author for the ground-truth SMPL poses dataset 

### ISSUE THREAD

**Issue by plussea** [Xinyu-Yi/TransPose#57]
请问能提供ground truth smpl pose数据的DIP作者邮箱吗，或者能直发一份ground truth smpl pose。我的邮箱[1919366379@qq.com](mailto:1919366379@qq.com)谢谢（纯学术研究）

**Comment by Xinyu-Yi** [comment]
Deep Inertial Poser: Learning to Reconstruct Human Pose from Sparse Inertial Measurements in Real Time

**Comment by Xinyu-Yi** [comment]
It seems that the DIP authors have put the data on the website https://dip.is.tuebingen.mpg.de/download.php.  You can check "ORIGINAL TotalCapture DATA W/ CORRESPONDING REFERENCE SMPL Poses (wo/ normalization, approx. 250MB)". But I'm not sure whether if it exactly matches the data I used. If you can reproduce the results with this, please tell me and I'll update the readme.
