### ISSUE TITLE
TotalCapture/official

### ISSUE THREAD

**Issue by whl-007** [Xinyu-Yi/TransPose#58]
您好，我想问问关于TotalCapture/official文件夹的事情，我下载了DIP的作者的TotalCapture数据集。他提供了DIP_recalculate的数据，但是我在他提供的gt和AMASS都没有找到您说的official gt文件，请问您在哪里下载的txt格式的 official gt呢，希望您能帮我解答这个问题
raw_totalcapture_official_dir = 'data/dataset_raw/TotalCapture/official'    # contain official gt (S1/acting1/gt_skel_gbl_pos.txt)

**Comment by Xinyu-Yi** [comment]
这个在TotalCapture数据集的官方网站上 https://cvssp.org/data/totalcapture/

**Comment by whl-007** [comment]
好的，谢谢，我现在无法登录进去下载它的数据集，我正在向Totalcapture的作者发邮件请求数据集
![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/c1055904-e603-47ff-a345-80111dfa8e92)
![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/51c9f560-f6a2-4925-90b3-6692e23bb85b)

**Comment by whl-007** [comment]
作者已经给我账号和密码啦，谢谢大佬！！

**Comment by whl-007** [comment]
另外想问问大佬，是要下载所有的s1到s5吗，
![Uploading image.png…]()
