### ISSUE TITLE
Clear order of the system input

### ISSUE THREAD

**Issue by AfterJourney00** [Xinyu-Yi/TransPose#6]
Hi, Xinyu
Thank you for releasing your excellent work!
I'm trying to feed my data into your network to get some results, but I wonder what's the exact order of the six imus, which is stated as `x = [a_root, ... ,a_rarm, R_root, ... ,R_rarm]` in the paper. Thank you!

**Comment by AfterJourney00** [comment]
The clear order is `larm, rarm, lleg, rleg, head, root(hip)`.

**Comment by Xinyu-Yi** [comment]
Sorry, I have just seen your question. You are right. The order should be `larm, rarm, lleg, rleg, head, root(hip)`
