### ISSUE TITLE
如何定标

### ISSUE THREAD

**Issue by whl-007** [Xinyu-Yi/TransPose#60]
你好，我捕获ground-truth使用的是反光点和vicon的光学动作捕捉系统，看到你的实时演示的imu定标的代码如下：
![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/f75d4ab6-8f75-495b-9b4e-fcc8bceaa3e0)
我看到你只对imu 1 定标，那么其他的imu就不用定标了是吗？我更想问的一个具体问题是你们使用的是光学动捕系统捕获的ground-truth吗？在imu定标的时候需要和光学动捕系统的x、y、z轴对齐是吗？那手动对齐岂不是会有很大的误差，还是说你们使用了其他特别的方法（比如T-pose解决了一些问题）呢？希望你能解决我的问题！

**Comment by whl-007** [comment]
我明白啦，非常感谢，我还有一个问题想问您，你是怎么把6个imu的坐标系对其的呢？我对你的代码的理解是先读取 IMU 数据并计算过去3秒中最后 buffer_len 帧测量的平均四元数和平均加速度，然后将四元数转换为旋转矩阵，之后就可以穿上imu设备和T-pose了，经过将四元数转换为旋转矩阵和T-pose操作之后是就可以将6个imu的坐标系进行对其了吗？

**Comment by whl-007** [comment]
哦哦！我发现您是不是在做动捕实验的时候将所有的imu的加速度数据和姿态角度信息都转换成 东北天 坐标系（ENU）中的加速度和角度信息来完成6个imu的坐标系对齐（都放在ENU坐标系下处理）呢？希望您能解答我的问题，非常感谢！

**Comment by Xinyu-Yi** [comment]
有磁力计所以不需要对齐每个IMU的全局坐标系。

**Comment by whl-007** [comment]
嗯嗯，确实在您的代码中找不到对齐六个imu坐标系的操作，但是正如您的论文附录中A.1 Calibration所说
![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/75372ccb-7701-4b93-9e37-bfffbc2e15f2)
![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/ec530acf-6604-41d7-8bab-a2aabc543c67)
将IMU与SMPL身体模型对应的坐标系进行对齐，是通过“ 在捕捉动作之前，首先将一个IMU放置在其传感器坐标系𝐹(𝑆)的轴与SMPL坐标系𝐹(𝑀)的相应轴对齐，即将IMU放置在真实世界中，使其𝑥轴指向左侧、𝑦轴指向上方和𝑧轴指向前方。然后，可以将方向测量𝑷(𝐼𝑀)视为从𝐹(𝐼)到𝐹(𝑀)的过渡矩阵：B(M)=B(I)P(IM)。 ”的方式对齐的，但是将IMU放置在真实世界中，使其𝑥轴指向左侧、𝑦轴指向上方和𝑧轴指向前方手动放置是不是会有非常大的误差呢？您在实验的时候具体是怎么操作的呢？通过这样的操作然后将imu的数据向smpl的人体姿势模型对齐就可以直接做实验，将imu的数据丢进您的网络预测了是嘛。

**Comment by whl-007** [comment]
大佬，我懂了，感谢你为我解惑！！

**Comment by whl-007** [comment]
你好，大佬，由于我的基础知识太薄弱了，导致我很多东西不明白，不知道是否可以加您的微信向您请教一些问题呢？我的微信是whl31155351，如果您能加我的微信为我解惑，我将不胜感激
