### ISSUE TITLE
Is there a bug in evaluation script?

### ISSUE THREAD

**Issue by syguan96** [Xinyu-Yi/TransPose#61]
When evaluating Transpose on DIP, you evaluate the mean error on each sequence and then average them. However, the sequence length is not equal, so you should save the errors of each sample and calculate the mean error on the whole dataset. Am I right?

**Comment by syguan96** [comment]
Update:
For Jitter, we should calculate on each sequence separately. For other metrics, we should calculate on the whole dataset.

**Comment by Xinyu-Yi** [comment]
> When evaluating Transpose on DIP, you evaluate the mean error on each sequence and then average them. However, the sequence length is not equal, so you should save the errors of each sample and calculate the mean error on the whole dataset. Am I right?

Yes. The results in the paper can be reproduced using the current evaluation method. But definitely you can use the new averaging method.
