### ISSUE TITLE
How do you analyze whether the ground truth (gt) footsteps are in contact with the ground?

### ISSUE THREAD

**Issue by whl-007** [Xinyu-Yi/TransPose#63]
![image](https://github.com/Xinyu-Yi/TransPose/assets/120098257/e153ac3f-3268-4b9c-9ccc-fa2d9e294ad8)
Hello, I noticed that you used a biRNN in Fig. 2 for estimating foot-ground contact.How can you analyze whether the ground truth (gt) footsteps are in contact with the ground? Which paper did you use to analyze whether footsteps are in the air/not in contact with the ground? I hope you can provide an answer for me!Thank you very much.

**Comment by Xinyu-Yi** [comment]
If a foot velocity is low, I mark it as contacting the ground (see the paper). So a stationary foot in the air will be also labeled as in contact, but this case does not often occur and on the other hand does not affect the result (for this TransPose paper). You may find that in PIP paper we add an additional condition on its height.

**Comment by whl-007** [comment]
Yes，yes，I discovered recently，thank you very much！
