### ISSUE TITLE
Joint positions

### ISSUE THREAD

**Issue by Amirhosein80** [Xinyu-Yi/TransPose#65]
Hi, I am currently working on writing a training code for your Pose model. I want to train Pose-S1 and Pose-S2 again, but I don’t know how i can calculate joint positions for training on DIP and Total Capture. Like AMASS can I use forward kinematics or not?

**Comment by Xinyu-Yi** [comment]
Yes, just use forward kinematics. After that, you need to transform the joint positions in the global frame to the root frame by subtracting the root position and left-multiplying it with the inverse root orientation.
