### ISSUE TITLE
Full Joint Vertex Index List?

### ISSUE THREAD

**Issue by bryanbocao** [Xinyu-Yi/TransPose#69]
Hi @Xinyu-Yi, thanks for sharing the awesome work! Can you help me find which indices correspond to which joints? I searched the code and paper but did not find them. It would be great to provide the full list of mapping an index to a joint name if I missed that. Specifically the mapping of [0-23] to joint names in https://github.com/bryanbocao/TransPose/blob/a3501996f7c5e99f9d0c6dae6a8db6c7d094df68/config.py#L30. Thanks!

**Comment by Xinyu-Yi** [comment]
Hi. It is defined by the SMPL model. The order is:
0. pelvis(root)
1. lhip
2. rhip
3. spine1
4. lknee
5. rknee
6. spine2
7. lankle
8. rankle
9. spine3
10. lfoot
11. rfoot
12. neck(lower neck)
13. lclavicle
14. rclavicle
15. head(upper neck)
16. lshoulder
17. rshoulder
18. lelbow
19. relbow
20. lwirst
21. rwrist
22. lhand
23. rhand

**Comment by bryanbocao** [comment]
@Xinyu-Yi Thanks for the full list!

**Comment by bryanbocao** [comment]
Hi @Xinyu-Yi, it would be great to further help me clarify:

Figure 3 in the paper mentions 6 IMUs ```(left forearm, right forearm, left lower leg, right lower leg, head and pelvis(root)``` as leaf joints while the implementation uses only 5:
https://github.com/Xinyu-Yi/TransPose/blob/4963e71ae33c3ea5ac24fcc053015804e9705ad1/config.py#L30-L31
which corresponds to ```[lankle, rankle, neck(lower neck), lwirst, rwrist]```.

It also differs from the IMUs in the ```process_dipimu()```:
https://github.com/Xinyu-Yi/TransPose/blob/4963e71ae33c3ea5ac24fcc053015804e9705ad1/preprocess.py#L95-L96
which corresponds to ```[lankle, rankle, rfoot, neck(lower neck), pelvis(root), rhip]```.

I am confused with this inconsistency. It would be great if you can clarify that.

---
**Update Y2025M02D16Sun**
This is because the paper has its own index list from 24 IMUs:
<img width="866" alt="Image" src="https://github.com/user-attachments/assets/bf27297e-8b86-413e-b1d1-65214c0bcfbb" />

while DIP-IMU has a different index list from 17 IMUs:
```
    https://github.com/FIGLAB/IMUPoser/blob/ca94eac4be156b5f16e6ed0d0953d0bac6084c1a/src/imuposer/config.py#L65-L83
    # DIP order
    # 0 head, # 1 spine2, # 2 belly, # 3 lchest, # 4 rchest, # 5 lshoulder, # 6 rshoulder, # 7 lelbow,
    # 8 relbow, # 9 lhip, # 10 rhip, # 11 lknee, # 12 rknee, # 13 lwrist, # 14 rwrist, # 15 lankle, # 16 rankle
```
so
https://github.com/Xinyu-Yi/TransPose/blob/4963e71ae33c3ea5ac24fcc053015804e9705ad1/preprocess.py#L95-L96
should correspond to ```[lelbow, relbow, lknee, rknee, head, belly]```, but still it does not match ```[lankle, rankle, rfoot, neck(lower neck), pelvis(root), rhip]``` exactly. It would be great to get more clarification.

**Comment by bryanbocao** [comment]
> Hi @Xinyu-Yi, it would be great to further help me clarify:
> 
> Figure 3 in the paper mentions 6 IMUs `(left forearm, right forearm, left lower leg, right lower leg, head and pelvis(root)` as leaf joints while the implementation uses only 5:
> 
> https://github.com/Xinyu-Yi/TransPose/blob/4963e71ae33c3ea5ac24fcc053015804e9705ad1/config.py#L30-L31
> 
> 
> which corresponds to `[lankle, rankle, neck(lower neck), lwirst, rwrist]`.
> It also differs from the IMUs in the `process_dipimu()`:
> 
> https://github.com/Xinyu-Yi/TransPose/blob/4963e71ae33c3ea5ac24fcc053015804e9705ad1/preprocess.py#L95-L96
> 
> 
> which corresponds to `[lankle, rankle, rfoot, neck(lower neck), pelvis(root), rhip]`.
> I am confused with this inconsistency. It would be great if you can clarify that.

The 5 IMUs ```[lankle, rankle, neck(lower neck), lwirst, rwrist]``` except the ```pelvis``` is mentioned in the paper, but for ```DIP_IMU``` dataset I do not quite understand why ```[lankle, rankle, rfoot, neck(lower neck), pelvis(root), rhip]``` are used, and why only ```rhip``` is used without ```lhip``` for balance purposes.

**Comment by bryanbocao** [comment]
Visualization in Slide 13
![Screenshot from 2024-11-14 19-23-56](https://github.com/user-attachments/assets/11a1b55f-fa33-4f11-b481-108a76c690e1)

and Slide 
![Screenshot from 2024-11-14 19-24-36](https://github.com/user-attachments/assets/3f36cc5b-751d-46af-b176-6cc81237518a)
23

https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf

**Comment by bryanbocao** [comment]
Visualization in Slide 13
![Screenshot from 2024-11-14 19-23-56](https://github.com/user-attachments/assets/11a1b55f-fa33-4f11-b481-108a76c690e1)

and Slide 23
![Screenshot from 2024-11-14 19-24-36](https://github.com/user-attachments/assets/3f36cc5b-751d-46af-b176-6cc81237518a)

https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf
