### ISSUE TITLE
Training or data synthesis code details

### ISSUE THREAD

**Issue by ChunhuiMa** [Xinyu-Yi/TransPose#7]
Hi Xinyu
Thx for your amazing job.
Would it be possible for you to share the training or data synthesis code，so that we can reproduce your results completely? 
The uncommented version also helped me a lot. 
weapon@pku.edu.cn  
Thanks again

**Comment by Oliver-ny** [comment]
Hi @Xinyu-Yi 
Thank you for your impressive job.
Our recent work lacks of data from the virtual IMUs. Could you please share the training or data synthesis code about the virtual IMUs?
niuyuan@cug.edu.cn
Anyway, thank you for your generous help.

**Comment by Xinyu-Yi** [comment]
Hi, I have released the AMASS synthesis code. You can check the preprocess.py if needed.
