### ISSUE TITLE
xsens复原项目求助

### ISSUE THREAD

**Issue by Oxyniu17** [Xinyu-Yi/TransPose#71]
您好欣宇学长，我是天津大学的一名本科生，目前我们尝试用xsensdot复原您的项目，但是遇到了很多困难，不知道您能不能给我们一些指导

**Comment by Oxyniu17** [comment]
方便加您个微信联系吗学长

**Comment by Xinyu-Yi** [comment]
您好，抱歉才回复您，您可以把您的联系方式发我邮件，我来加您

**Comment by cloudy158** [comment]
> 您好欣宇学长，我是天津大学的一名本科生，目前我们尝试用xsensdot复原您的项目，但是遇到了很多困难，不知道您能不能给我们一些指导

你好，你们复原成功了吗，我也在复现这个项目，但是遇到了一些问题，希望交流一下，我的微信是lx15874536575
